### ISSUE TITLE
Standardize gem name

### ISSUE THREAD

**Issue by ghousemohamed** [bigbinary/email_prefixer#3]
Ref: https://github.com/bigbinary/neeto-engineering-web/issues/244

- [ ] Gem name should be equal to repo name ( neeto-email-prefixer ) Repo name will be updated before the release
- [x]  Update file and folder names accordingly
- [x] Add proper Namespaces like https://github.com/bigbinary/neeto-team-members-engine/blob/main/app/services/neeto_team_members_engine/permission_seeder_service.rb
- [x] Update the gem name in all places where it is being used (eg: Gemfile.commom.rb)

**Comment by abhishekt98** [comment]
@ghousemohamed _a Please assign this to someone

**Comment by ghousemohamed** [comment]
@Nuzair46 _a

**Comment by sumanranjanpanda** [comment]
@AbhayVAshokan _a Please work on this.
